### PR TITLE
[#6] Add Poetry Executable Check

### PR DESCRIPTION
**Pull request by lucasvieirasilva**
This PR modifies all the executors and generators to check if the `poetry` is installed before running any poetry command.

### CODE REVIEW

**Comment by niall-mediasuite** [comment]
Thanks for the quick turn around on this. Looking through the PR I have noticed that while this fixes the issue of detecting if poetry is installed explicitly it doesn't solve any other issues if the command returns an error. It would also be useful to check the error result from `spawn.sync` and fail the command if it fails.

**Comment by lucasvieirasilva** [comment]
@niall-mediasuite you are right, I've created an issue https://github.com/lucasvieirasilva/nx-plugins/issues/12, I'm gonna work on that tomorrow, many thanks

**Comment by niall-mediasuite** [comment]
No problem. Great work its an awesome plugin.

**Comment by lucasvieirasilva** [comment]
@niall-mediasuite many thanks, glad you like it

**Pull request merged**
